"""AUTO-GENERATED by scripts/generate_reference_snippet_outputs.py — do not edit."""

def collect(row, enabled):
    # generated from snippets/comment/root.py:11 {field_name}
    rows = []
    # normalize row
    # then append it
    rows.append(dict(row))
    if enabled:
        # nothing to do
        # here
        pass
    return rows

