"""AUTO-GENERATED by scripts/generate_reference_snippet_outputs.py — do not edit."""

class GeneratedGetter:
    default = 42

    def fetch(self, item):
        result = []
        result.append(9)
        return result
