"""AUTO-GENERATED by scripts/generate_reference_snippet_outputs.py — do not edit."""

events = []
events.append('first')
events__astichi_scoped_1.append('second')
events__astichi_scoped_2 = events
events__astichi_scoped_2.append('third')
result = events
