"""AUTO-GENERATED by scripts/generate_reference_snippet_outputs.py — do not edit."""

events = []
__astichi_assign__inst__Pipeline__ref__Root__name__events.append('first')
events.append('second')
events__astichi_scoped_1 = events
events__astichi_scoped_1.append('third')
result = events
__astichi_assign__inst__Pipeline__ref__Root__name__events = events
