"""AUTO-GENERATED by scripts/generate_reference_snippet_outputs.py — do not edit."""

class Accessors:

    def __init__(self, data):
        self._data = data

    def get_name(self):
        return self._data['name']

    def get_email(self):
        return self._data['email']

    def get_age(self):
        return self._data['age']
