"""AUTO-GENERATED by scripts/generate_reference_snippet_outputs.py — do not edit."""

def load(user):
    return user

def configure(limit: int=10, *, debug=False):
    return (limit, debug)

def collect(*items, **options):
    return (items, options)

def run_request(session):
    seen = session
    session__astichi_scoped_1 = 'local'
    local_session = session__astichi_scoped_1
    return session
