"""AUTO-GENERATED by scripts/generate_reference_snippet_outputs.py — do not edit."""

def generate_dict(function):
    return lambda ctxt: function(a=ctxt['a'], b=ctxt['b'], c=ctxt['c'])

def call_attr(function, cls_ctx):
    return function(a=cls_ctx.a, b=cls_ctx.b, c=cls_ctx.c)
