"""AUTO-GENERATED by scripts/generate_reference_snippet_outputs.py — do not edit."""

result = []
result.append('step-0')
result.append('step-1')
result.append('step-2')
result.append('step-2-extra')
result.append('step-3')
final = tuple(result)
