"""Marker recognition and lowering bridge for Astichi."""

from astichi.lowering.call_argument_payloads import (
    PayloadLocalDirective,
    DirectiveFuncArgItem,
    DoubleStarFuncArgItem,
    FuncArgPayload,
    FuncArgPayloadItem,
    KeywordFuncArgItem,
    PositionalFuncArgItem,
    StarredFuncArgItem,
    collect_payload_local_directives,
    direct_funcargs_directive_calls,
    extract_funcargs_payload,
    is_astichi_funcargs_call,
    lower_payload_for_region,
    register_explicit_keyword,
    validate_payload_for_region,
    validate_call_argument_payload_surface,
)
from astichi.lowering.boundaries import (
    group_markers_by_astichi_scope,
    validate_boundary_interaction_matrix,
    validate_boundary_marker_placement,
)
from astichi.lowering.external_bind import apply_external_bindings
from astichi.lowering.external_ref import (
    apply_external_ref_lowering,
    desugar_external_ref_kwargs,
    validate_external_ref_surface,
)
from astichi.lowering.markers import (
    MARKERS_BY_NAME,
    MarkerSpec,
    PortTemplate,
    RecognizedMarker,
    recognize_markers,
)
from astichi.lowering.parameters import (
    PARAMS_PAYLOAD_NAME,
    extract_params_payload_from_body,
    has_params_payload,
    is_astichi_params_def,
    param_hole_name,
    validate_parameter_hole_surface,
    validate_parameter_payload_surface,
)

__all__ = [
    "MARKERS_BY_NAME",
    "DirectiveFuncArgItem",
    "DoubleStarFuncArgItem",
    "FuncArgPayload",
    "FuncArgPayloadItem",
    "KeywordFuncArgItem",
    "MarkerSpec",
    "PayloadLocalDirective",
    "PARAMS_PAYLOAD_NAME",
    "PortTemplate",
    "PositionalFuncArgItem",
    "RecognizedMarker",
    "StarredFuncArgItem",
    "apply_external_bindings",
    "apply_external_ref_lowering",
    "collect_payload_local_directives",
    "desugar_external_ref_kwargs",
    "direct_funcargs_directive_calls",
    "extract_funcargs_payload",
    "extract_params_payload_from_body",
    "group_markers_by_astichi_scope",
    "has_params_payload",
    "is_astichi_funcargs_call",
    "is_astichi_params_def",
    "lower_payload_for_region",
    "param_hole_name",
    "recognize_markers",
    "register_explicit_keyword",
    "validate_call_argument_payload_surface",
    "validate_boundary_interaction_matrix",
    "validate_boundary_marker_placement",
    "validate_external_ref_surface",
    "validate_parameter_hole_surface",
    "validate_parameter_payload_surface",
    "validate_payload_for_region",
]
