"""Marker recognition and lowering bridge for Astichi."""

from astichi.lowering.call_argument_payloads import (
    DOUBLE_STAR_FUNC_ARG_REGION,
    PLAIN_FUNC_ARG_REGION,
    PayloadLocalDirective,
    STARRED_FUNC_ARG_REGION,
    DirectiveFuncArgItem,
    DoubleStarFuncArgItem,
    FuncArgPayload,
    FuncArgPayloadItem,
    FuncArgRegion,
    KeywordFuncArgItem,
    PositionalFuncArgItem,
    StarredFuncArgItem,
    collect_payload_local_directives,
    direct_funcargs_directive_calls,
    extract_funcargs_payload,
    is_astichi_funcargs_call,
    lower_payload_for_region,
    register_explicit_keyword,
    validate_payload_for_region,
    validate_call_argument_payload_surface,
)
from astichi.lowering.boundaries import (
    group_markers_by_astichi_scope,
    validate_boundary_interaction_matrix,
    validate_boundary_marker_placement,
)
from astichi.lowering.external_bind import apply_external_bindings
from astichi.lowering.external_ref import (
    apply_external_ref_lowering,
    desugar_external_ref_kwargs,
    evaluate_restricted_path_expression,
    extract_dotted_reference_chain,
    validate_external_ref_surface,
)
from astichi.lowering.marker_contexts import (
    CALL_CONTEXT,
    DECORATOR_CONTEXT,
    DEFINITIONAL_CONTEXT,
    IDENTIFIER_CONTEXT,
    MarkerContext,
)
from astichi.lowering.markers import (
    MARKERS_BY_NAME,
    MarkerSpec,
    PortTemplate,
    RecognizedMarker,
    StatementPrefixScan,
    marker_metadata_name_node_ids,
    marker_metadata_name_nodes,
    recognize_markers,
    scan_statement_prefix,
)
from astichi.lowering.parameters import (
    PARAMS_PAYLOAD_NAME,
    extract_params_payload_from_body,
    has_params_payload,
    is_astichi_params_def,
    param_hole_name,
    validate_parameter_hole_surface,
    validate_parameter_payload_surface,
)

__all__ = [
    "MARKERS_BY_NAME",
    "CALL_CONTEXT",
    "DECORATOR_CONTEXT",
    "DEFINITIONAL_CONTEXT",
    "DirectiveFuncArgItem",
    "DoubleStarFuncArgItem",
    "DOUBLE_STAR_FUNC_ARG_REGION",
    "FuncArgPayload",
    "FuncArgPayloadItem",
    "FuncArgRegion",
    "IDENTIFIER_CONTEXT",
    "KeywordFuncArgItem",
    "MarkerContext",
    "MarkerSpec",
    "PayloadLocalDirective",
    "PARAMS_PAYLOAD_NAME",
    "PLAIN_FUNC_ARG_REGION",
    "PortTemplate",
    "PositionalFuncArgItem",
    "RecognizedMarker",
    "StatementPrefixScan",
    "StarredFuncArgItem",
    "STARRED_FUNC_ARG_REGION",
    "apply_external_bindings",
    "apply_external_ref_lowering",
    "collect_payload_local_directives",
    "desugar_external_ref_kwargs",
    "evaluate_restricted_path_expression",
    "extract_dotted_reference_chain",
    "direct_funcargs_directive_calls",
    "extract_funcargs_payload",
    "extract_params_payload_from_body",
    "group_markers_by_astichi_scope",
    "has_params_payload",
    "is_astichi_funcargs_call",
    "is_astichi_params_def",
    "lower_payload_for_region",
    "marker_metadata_name_node_ids",
    "marker_metadata_name_nodes",
    "param_hole_name",
    "recognize_markers",
    "register_explicit_keyword",
    "validate_call_argument_payload_surface",
    "validate_boundary_interaction_matrix",
    "validate_boundary_marker_placement",
    "validate_external_ref_surface",
    "validate_parameter_hole_surface",
    "validate_parameter_payload_surface",
    "validate_payload_for_region",
    "scan_statement_prefix",
]
