"""Experimental assembler helpers for inventory-driven builder wiring."""

from astichi.assembler.client import BuildIndex
from astichi.assembler.runner import AssemblyRunner
from astichi.assembler.production import (
    BindingSpec,
    BuildProductionSpec,
    ProductionCatalog,
    ProductionRequest,
    ProductionSpec,
    ProductionTemplateProvider,
    ProductionValueProvider,
    SourceProvider,
    TargetSpec,
    TemplateChoice,
    TemplateProducerSpec,
    build_production_roots,
)
from astichi.assembler.scope import (
    AssemblyScope,
    BindingCandidate,
    BindingResource,
    ComposableCandidate,
    ComposableResource,
    DemandSelector,
    ExternalValue,
    ExternalValueCandidate,
    ExternalValueResource,
    IdentifierNameCandidate,
    IdentifierNameResource,
    as_composable,
    as_external_value,
    as_identifier,
    code_owner_parts,
    find_candidates,
    require_one,
)

__all__ = [
    "AssemblyRunner",
    "AssemblyScope",
    "BindingCandidate",
    "BindingSpec",
    "BindingResource",
    "BuildIndex",
    "BuildProductionSpec",
    "ComposableCandidate",
    "ComposableResource",
    "DemandSelector",
    "ExternalValue",
    "ExternalValueCandidate",
    "ExternalValueResource",
    "IdentifierNameCandidate",
    "IdentifierNameResource",
    "ProductionCatalog",
    "ProductionRequest",
    "ProductionSpec",
    "ProductionTemplateProvider",
    "ProductionValueProvider",
    "SourceProvider",
    "TargetSpec",
    "TemplateChoice",
    "TemplateProducerSpec",
    "as_composable",
    "as_external_value",
    "as_identifier",
    "build_production_roots",
    "code_owner_parts",
    "find_candidates",
    "require_one",
]
