"""AUTO-GENERATED by scripts/generate_reference_snippet_outputs.py — do not edit."""

events = []
events__astichi_scoped_1 = events
events__astichi_scoped_1.append('first')
events__astichi_scoped_2 = events
events__astichi_scoped_2.append('second')
events__astichi_scoped_3 = events
events__astichi_scoped_3.append('third')
final = tuple(events)
