"""Immutable semantic carrier types for Astichi."""

from astichi.model.basic import BasicComposable
from astichi.model.composable import Composable
from astichi.model.descriptors import (
    AddPolicy,
    ComposableDescription,
    ComposableHole,
    ExternalBindDescriptor,
    HoleDescriptor,
    IdentifierDemandDescriptor,
    IdentifierSupplyDescriptor,
    MULTI_ADD,
    PortDescriptor,
    ProductionDescriptor,
    SINGLE_ADD,
    TargetAddress,
)
from astichi.model.external_values import (
    MAX_EXTERNAL_VALUE_DEPTH,
    validate_external_value,
    value_to_ast,
)
from astichi.model.origin import CompileOrigin
from astichi.model.ports import (
    ARG_IDENTIFIER_ORIGIN,
    BIND_EXTERNAL_ORIGIN,
    IDENTIFIER,
    PARAMETER,
    BLOCK_PLACEMENT,
    CALL_ARGUMENT_PLACEMENT,
    CONST_MUTABILITY,
    DemandPort,
    EXPRESSION_PLACEMENT,
    EXPORT_ORIGIN,
    HOLE_ORIGIN,
    IDENTIFIER_PLACEMENT,
    IMPORT_ORIGIN,
    INSERT_ORIGIN,
    PARAMETER_HOLE_ORIGIN,
    PARAMETER_PAYLOAD_ORIGIN,
    PASS_ORIGIN,
    PortMutability,
    PortOrigin,
    PortOrigins,
    PortPlacement,
    SIGNATURE_PARAMETER_PLACEMENT,
    SupplyPort,
    extract_demand_ports,
    extract_supply_ports,
    validate_port_pair,
)

__all__ = [
    "ARG_IDENTIFIER_ORIGIN",
    "AddPolicy",
    "BIND_EXTERNAL_ORIGIN",
    "BLOCK_PLACEMENT",
    "CALL_ARGUMENT_PLACEMENT",
    "BasicComposable",
    "Composable",
    "ComposableDescription",
    "ComposableHole",
    "CompileOrigin",
    "CONST_MUTABILITY",
    "DemandPort",
    "EXPRESSION_PLACEMENT",
    "ExternalBindDescriptor",
    "EXPORT_ORIGIN",
    "HoleDescriptor",
    "HOLE_ORIGIN",
    "IDENTIFIER",
    "IDENTIFIER_PLACEMENT",
    "IdentifierDemandDescriptor",
    "IdentifierSupplyDescriptor",
    "IMPORT_ORIGIN",
    "INSERT_ORIGIN",
    "PARAMETER",
    "PARAMETER_HOLE_ORIGIN",
    "PARAMETER_PAYLOAD_ORIGIN",
    "PASS_ORIGIN",
    "PortMutability",
    "PortOrigin",
    "PortOrigins",
    "PortPlacement",
    "ProductionDescriptor",
    "SIGNATURE_PARAMETER_PLACEMENT",
    "SINGLE_ADD",
    "MAX_EXTERNAL_VALUE_DEPTH",
    "MULTI_ADD",
    "SupplyPort",
    "TargetAddress",
    "PortDescriptor",
    "extract_demand_ports",
    "extract_supply_ports",
    "validate_external_value",
    "validate_port_pair",
    "value_to_ast",
]
