"""AUTO-GENERATED by scripts/generate_reference_snippet_outputs.py — do not edit."""

result = []
shared = 10
__astichi_assign__inst__Pipeline__ref__Root__ref__Cell__name__shared = shared
result.append(__astichi_assign__inst__Pipeline__ref__Root__ref__Cell__name__shared + 5)
final = tuple(result)
