#!/usr/bin/env python3
"""Walk docs/reference/snippets and write materialized Python beside sources.

Each output file is named ``<stem>_generated.py`` in the same directory as the
authored root: a flat snippet ``foo.py`` → ``foo_generated.py``; a bundle
directory ``bar/`` → ``bar/bar_generated.py``.

Standalone snippets: optional first line
  # astichi-snippet: {"bind": {...}, "bind_identifier": {...}, "arg_names": {...}}

Builder bundles: either

  - snippet.json + fragment .py files (see below), or
  - recipe.py defining ``def run() -> str:`` returning final generated source

snippet.json shape:

  {
    "instances": {
      "Root": "root.py",
      "Impl": {"file": "impl.py", "arg_names": {"seed": "source_value"}}
    },
    "wires": ["builder.Root.body.add.Impl()", ...],
    "unroll": false
  }

Each instance value is either a fragment filename string or an object with
``"file"`` plus optional ``astichi.compile`` kwargs (e.g. ``arg_names``).

Run from astichi/: uv run python scripts/generate_reference_snippet_outputs.py
"""
from __future__ import annotations

import ast
import json
import re
import sys
from pathlib import Path

_SNIPPET_META = re.compile(r"^#\s*astichi-snippet:\s*(\{.*\})\s*\n?", re.M)

# astichi package (editable) — scripts/ lives next to docs/
_ASTICHI_ROOT = Path(__file__).resolve().parent.parent
_SNIPPETS = _ASTICHI_ROOT / "docs" / "reference" / "snippets"


def _strip_meta(source: str) -> tuple[dict, str]:
    m = _SNIPPET_META.match(source)
    if not m:
        return {}, source
    meta = json.loads(m.group(1))
    return meta, source[m.end() :].lstrip("\n")


def _apply_compile_kwargs(meta: dict) -> dict:
    out = {}
    if "arg_names" in meta:
        out["arg_names"] = meta["arg_names"]
    return out


def _normalize_bind_kwargs(raw: dict) -> dict:
    out: dict = {}
    for k, v in raw.items():
        if isinstance(v, list):
            out[k] = tuple(v)
        else:
            out[k] = v
    return out


def _materialize_flat(py_path: Path) -> str:
    import astichi

    raw = py_path.read_text(encoding="utf-8")
    meta, body = _strip_meta(raw)
    composable = astichi.compile(
        body.strip() + "\n",
        file_name=py_path.name,
        **_apply_compile_kwargs(meta),
    )
    if "bind" in meta:
        composable = composable.bind(**_normalize_bind_kwargs(meta["bind"]))
    if "bind_identifier" in meta:
        composable = composable.bind_identifier(**meta["bind_identifier"])
    return ast.unparse(composable.materialize().tree)


def _run_recipe(recipe_path: Path) -> str:
    """Execute ``recipe.py`` (must define ``run()`` -> unparsed source str)."""
    import astichi
    import textwrap

    g: dict = {"ast": ast, "astichi": astichi, "textwrap": textwrap}
    code = recipe_path.read_text(encoding="utf-8")
    exec(compile(code, str(recipe_path), "exec"), g)  # noqa: S102
    run = g.get("run")
    if not callable(run):
        raise ValueError(f"{recipe_path} must define run() -> str")
    return run()


def _compile_bundle_fragment(bundle_dir: Path, inst: object) -> object:
    """Compile a fragment; ``inst`` is a filename or ``{file, ...compile kwargs}``."""
    import astichi

    if isinstance(inst, str):
        fname = inst
        compile_kw: dict = {}
    elif isinstance(inst, dict):
        fname = inst["file"]
        compile_kw = {k: v for k, v in inst.items() if k != "file"}
    else:
        raise TypeError(f"invalid instance spec: {inst!r}")
    sub = (bundle_dir / fname).read_text(encoding="utf-8")
    _, body = _strip_meta(sub)
    return astichi.compile(
        body.strip() + "\n",
        file_name=fname,
        **compile_kw,
    )


def _materialize_bundle(bundle_dir: Path, spec: dict) -> str:
    import astichi

    b = astichi.build()
    for name, inst in spec["instances"].items():
        c = _compile_bundle_fragment(bundle_dir, inst)
        getattr(b.add, name)(c)
    for wire in spec.get("wires", []):
        eval(wire, {"builder": b})  # noqa: S307
    merged = b.build(unroll=bool(spec.get("unroll", False)))
    return ast.unparse(merged.materialize().tree)


def _write_generated(dest: Path, text: str) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(
        f'"""AUTO-GENERATED by scripts/generate_reference_snippet_outputs.py — do not edit."""\n\n{text}\n',
        encoding="utf-8",
    )


def main() -> int:
    if not _SNIPPETS.is_dir():
        print(f"missing snippets dir: {_SNIPPETS}", file=sys.stderr)
        return 1

    generated: list[Path] = []

    for topic in sorted(_SNIPPETS.iterdir()):
        if not topic.is_dir() or topic.name.startswith("_"):
            continue
        for py_path in sorted(topic.glob("*.py")):
            if py_path.name.startswith("_"):
                continue
            if py_path.name.endswith("_generated.py"):
                continue
            dest = py_path.parent / f"{py_path.stem}_generated.py"
            try:
                out = _materialize_flat(py_path)
            except Exception as e:
                print(f"FAIL {py_path}: {e}", file=sys.stderr)
                raise
            _write_generated(dest, out)
            generated.append(dest)
        for bundle in sorted(topic.iterdir()):
            if not bundle.is_dir():
                continue
            recipe = bundle / "recipe.py"
            sj = bundle / "snippet.json"
            dest = bundle / f"{bundle.name}_generated.py"
            if recipe.is_file():
                try:
                    out = _run_recipe(recipe)
                except Exception as e:
                    print(f"FAIL {bundle}: {e}", file=sys.stderr)
                    raise
                _write_generated(dest, out)
                generated.append(dest)
            elif sj.is_file():
                spec = json.loads(sj.read_text(encoding="utf-8"))
                try:
                    out = _materialize_bundle(bundle, spec)
                except Exception as e:
                    print(f"FAIL {bundle}: {e}", file=sys.stderr)
                    raise
                _write_generated(dest, out)
                generated.append(dest)

    print(f"wrote {len(generated)} file(s) alongside sources under {_SNIPPETS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
