[package]
name = "astichi_native_engine"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "_astichi_native_engine"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28.3", features = ["extension-module", "abi3-py38"] }
rustpython-parser = "0.4.0"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
