"""AUTO-GENERATED by scripts/generate_reference_snippet_outputs.py — do not edit."""

trace = []
leaf_tag = 'leaf-a'
trace.append(leaf_tag)
leaf_tag__astichi_scoped_1 = 'leaf-b'
trace.append(leaf_tag__astichi_scoped_1)
leaf_tag__astichi_scoped_2 = 'leaf-a'
trace.append(leaf_tag__astichi_scoped_2)
leaf_tag__astichi_scoped_3 = 'leaf-b'
trace.append(leaf_tag__astichi_scoped_3)
result = trace
