"""Internal lower-engine reference implementation."""

from astichi.lower_engine.catalog import (
    current_plus_future_surface_bundle_spec,
    current_surface_bundle_spec,
)
from astichi.lower_engine.engine import LowerEngine
from astichi.lower_engine.errors import LowerEngineError, StaleHandleError
from astichi.lower_engine.facade import (
    LowerTemplateBinding,
    LowerTemplateCache,
    NativeTemplateCache,
    copy_composable_executable_ast,
    copy_composable_template_ast,
    copy_template_ast,
    ensure_current_surface_bundle,
    ensure_current_native_surface_bundle,
    register_lower_template_binding,
    register_inventory_template,
    register_native_template_source,
    render_composable_source,
)
from astichi.lower_engine.handles import (
    EdgeId,
    LocatorId,
    OccurrenceId,
    OverlayId,
    OperationId,
    PatternId,
    RecordId,
    SurfaceId,
    TemplateId,
    TemplateRecordId,
)
from astichi.lower_engine.materialization import (
    HygieneOperation,
    MaterializationOperation,
    MaterializationPlan,
    build_materialization_plan,
)
from astichi.lower_engine.native import (
    EngineSelectionEvent,
    NativeExtensionUnavailableError,
    load_native_extension,
    native_capabilities,
    native_self_test,
    requested_lower_engine,
    select_lower_engine,
)
from astichi.lower_engine.registry import (
    BundleSchemaMismatchError,
    CompatibilityDecision,
    CompatibilityRuleSpec,
    OperationSpec,
    PatternSpec,
    RegisteredSurfaceBundle,
    ResultPolicyDescriptor,
    ShapeFieldExpectation,
    ShapePredicateDescriptor,
    SurfaceBundleSpec,
    SurfaceRegistry,
    SurfaceSpec,
)
from astichi.lower_engine.templates import TemplateRecordSpec

__all__ = [
    "BundleSchemaMismatchError",
    "CompatibilityDecision",
    "CompatibilityRuleSpec",
    "EdgeId",
    "EngineSelectionEvent",
    "HygieneOperation",
    "LocatorId",
    "LowerEngine",
    "LowerEngineError",
    "LowerTemplateBinding",
    "LowerTemplateCache",
    "NativeTemplateCache",
    "MaterializationOperation",
    "MaterializationPlan",
    "NativeExtensionUnavailableError",
    "OccurrenceId",
    "OperationId",
    "OperationSpec",
    "OverlayId",
    "PatternId",
    "PatternSpec",
    "RecordId",
    "RegisteredSurfaceBundle",
    "ResultPolicyDescriptor",
    "ShapeFieldExpectation",
    "ShapePredicateDescriptor",
    "StaleHandleError",
    "SurfaceBundleSpec",
    "SurfaceId",
    "SurfaceRegistry",
    "SurfaceSpec",
    "TemplateId",
    "TemplateRecordId",
    "TemplateRecordSpec",
    "build_materialization_plan",
    "copy_composable_executable_ast",
    "copy_composable_template_ast",
    "copy_template_ast",
    "current_plus_future_surface_bundle_spec",
    "current_surface_bundle_spec",
    "ensure_current_native_surface_bundle",
    "ensure_current_surface_bundle",
    "load_native_extension",
    "native_capabilities",
    "native_self_test",
    "requested_lower_engine",
    "register_lower_template_binding",
    "register_inventory_template",
    "register_native_template_source",
    "render_composable_source",
    "select_lower_engine",
]
