"""AUTO-GENERATED by scripts/generate_reference_snippet_outputs.py — do not edit."""

settings = {'mode': 'fast', 'enabled': True, 'timeout': 30}
labels = {'service': 'api', 'env': 'prod', 'region': 'apac', 'tier': 'edge'}
lookup = {'id': 'primary', 'name': 'display', 'email': 'contact'}
scoped = {(value := 1): value, 1: ((value__astichi_scoped_1 := 2), value__astichi_scoped_1)}
